name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: packages
      run: |
        sudo apt -y install debhelper pkgconf automake libtool cmake qt5-default qt5-qmake qtbase5-dev qttools5-dev-tools lsb-release
    - name: libraries
      run: |
        cd libqmqtt
        qmake
        make -j$(nproc)
        sudo make install
    - name: build
      run: |
        cd ..
        qmake
        make
    - name: make
      run: make
